back/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('front.urls'))
]

front/urls.py
from rest_framework import routers
from .api import ProjectviewSet
from django.contrib import admin
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    path('', views.home, name='home'),
    path('login/',views.login, name="login"),
    path('jokes/',views.jokes, name="Get_Jokes"),
    path('my_jokes/<str:email>',views.myjokes, name="My_Jokes"),
    path('getjokes/<str:uuid>',views.getjokes, name="GET"),
    path('addjoke/<str:ur>/<str:email>',views.addjoke, name="GET"),
    path('list_jokes/',views.listjokes, name="listjokes"),
    path('list_joke/<str:uuid>',views.listjoke, name="listJoke"),
    path('update_joke/<str:ids>',views.updatejoke, name="updateJoke"),
    path('delete_joke/<str:ids>',views.deletejoke, name="deleteJoke"),
    path('create_joke/',views.createjoke, name="createJoke"),
    
    
    
    
]

front/models.py
from django.db import models
from rest_framework import serializers

# Create your models here.
class Project(models.Model):
    idChiste=models.CharField(max_length=200)
    value= models.TextField()
    url= models.CharField(max_length=150)
    user= models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    

front/views.py
from django.shortcuts import render
import requests
from rest_framework.decorators import api_view
from django.http import HttpResponse
from decouple import config
from .funtions import *
from django.http import JsonResponse
import json
from .serializers import *
from .api import ProjectviewSet


class HttpResponseNoContent(HttpResponse):
    status_code = 204


def home(request):
    return render(request, "home.html")


def login(request):
    return render(request, "login.html")


def jokes(request):
    email = request.GET.get("email")
    emailregister = "algarcia677@misena.edu.co"
    mensaje = "User No register please login"
    if email != emailregister:
        return render(request, "login.html", {"mensaje": mensaje})
    else:
        uuid = enviocorreo(email)
        return render(request, "getJokes.html", {"user": uuid, "email": email})


def getjokes(_request, uuid):
    data = peticionchiste(uuid)
    return JsonResponse(data)

def myjokes(request,email):
    url = f"https://pqgqtixklmpmahgbiboa.supabase.co/rest/v1/products?user=eq.{email}&select=*"

    headers = {
        "Content-Type": "application/json",
        "Authorization": config("JWT"),
        "apikey": config("API_KEY"),
    }
    try:
        response = requests.get(url, headers=headers)
        data = response.json()
        values = []
        for i in data:
            values.append(i.get('value'))
        return render(request, "myJokes.html", {"values" : values, "user": email })

    except Exception as err:
        print(err)
        return render(request, "myJokes.html")



def addjoke(_request, ur, email):

    date = getdatajoke(ur)
    url = "https://pqgqtixklmpmahgbiboa.supabase.co/rest/v1/products"
    headers = {
        "Content-Type": "application/json",
        "Authorization": config("JWT"),
        "apikey": config("API_KEY"),
    }
    data = {
        "idChiste": date.get("id"),
        "value": date.get("value"),
        "url": date.get("url"),
        "user": email,
    }
    try:
        response = requests.post(url=url, json=data, headers=headers)
        return JsonResponse(response, safe=False)
    except Exception as err:
        print(response)
        return JsonResponse(err)


@api_view(["GET"])
def listjokes(_request):

    url = "https://pqgqtixklmpmahgbiboa.supabase.co/rest/v1/products?select=*"

    headers = {
        "Content-Type": "application/json",
        "Authorization": config("JWT"),
        "apikey": config("API_KEY"),
    }
    try:
        response = requests.get(url, headers=headers)
        return JsonResponse(response.json(), safe=False)
    except Exception as err:
        print(err)


@api_view(["GET"])
def listjoke(_request, user):

    url = f"https://pqgqtixklmpmahgbiboa.supabase.co/rest/v1/products?user=eq.{user}&select=*"

    headers = {
        "Content-Type": "application/json",
        "Authorization": config("JWT"),
        "apikey": config("API_KEY"),
    }
    try:
        response = requests.get(url, headers=headers)
        return JsonResponse(response.json(), safe=False)
    except Exception as err:
        print(err)


@api_view(["PATCH"])
def updatejoke(request, ids):
    values = request.body.decode("utf-8")
    body = json.loads(values)

    url = f"https://pqgqtixklmpmahgbiboa.supabase.co/rest/v1/products"
    headers = {
        "Content-Type": "application/json",
        "Authorization": config("JWT"),
        "apikey": config("API_KEY"),
    }

    params = {"id": f"eq.{ids}"}
    print(body)
    try:
        response = requests.patch(url, json=body, params=params, headers=headers)
        if response.status_code == 204:
            return JsonResponse(response.status_code, safe=False)
    except Exception as err:
        return JsonResponse(err.response.status_code)


@api_view(["DELETE"])
def deletejoke(request, ids):
    url = f"https://pqgqtixklmpmahgbiboa.supabase.co/rest/v1/products"
    headers = {
        "Content-Type": "application/json",
        "Authorization": config("JWT"),
        "apikey": config("API_KEY"),
    }
    params = {"id": f"eq.{ids}"}
    try:
        response = requests.delete(url=url, params=params, headers=headers)
        return JsonResponse(response.status_code, safe=False)
    except Exception as err:
        return JsonResponse(err)


@api_view(["POST"])
def createjoke(request):
    values = request.body.decode("utf-8")
    body = json.loads(values)

    url = "https://pqgqtixklmpmahgbiboa.supabase.co/rest/v1/products"
    headers = {
        "Content-Type": "application/json",
        "Authorization": config("JWT"),
        "apikey": config("API_KEY"),
    }
    data = {
        "idChiste": body["idChiste"],
        "value": body["value"],
        "url": body["url"],
        "user": body["user"],
    }
    try:
        response = requests.post(url=url, json=data, headers=headers)
        print(response)
        return JsonResponse(response.status_code, safe=False)
    except Exception as err:
        return JsonResponse(err)

front/templates/getJokes.html
{% extends 'layout.html' %}
{% block content %}

 <div class="card" style="width: 18rem;">
    <div class="card-body">
      <input type="hidden" name="user" id="user" value="{{ user }}">
      <input type="hidden" name="email" id="email" value="{{ email }}">

      <h5 class="card-title">Chistesito de Chuck </h5>
      <p class="card-text" id="descripcion"></p>
      <button id="btnList" class="btn btn-primary">Get Jokes</button>
      <button id="btnAdd" class="btn btn-danger">A favorito </button>
      
      <a href="{% url 'post:Get_Jokes'%}"><button id="btnmyjokes" class="btn btn-secundary">jokes</button></a>

    </div>
  </div>

{% endblock %}

front/templates/home.html
{% extends 'layout.html' %} {% block content %}

<div class="container">  
      <h1 class"text-center">Home</h1>
</div>
{% endblock %}

front/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous" />
  <title>Login</title>
</head>

  <body style="background-color:#fffgg;">
  {% include './partials/_navbar.html' %}

  <div class="container p-5 text-center" style="display: flex; justify-content: center;">
    {% block content %}
    {% endblock %}
  </div>
  <script src="{% static 'js/index.js'%}"></script>
</body>
</html>

front/templates/login.html
{% extends 'layout.html' %} {% block content %}

<div class="container">
  <div class="col-md-4 offset-md-4">
    <form action="{% url 'post:Get_Jokes' %}"  class="card card-body p-5">
      <h1 class="h4">Login</h1>
      <div class="form-check my-2 p-0">
        <input
          type="email"
          id="email"
          name="email"
          placeholder="youremail@site.com"
          class="form-input"
        />
      </div>
      <button class="btn btn-secondary">Send</button>
      <h1 class="h1">{{ mensaje }} </h1>
    </form>
  </div>
</div>
{% endblock %}

front/templates/myJokes.html
{% extends 'layout.html' %}
{% block content %}

{% for val in values %}
<div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">Your Joke </h5>
        <p class="card-text">{{ val }} </p>
    </div>
</div>
{% endfor %}

{% endblock %}

front/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'post:home' %}">Home</a>
    <a class="navbar-brand" href="{% url 'post:login' %}">Login</a>
    
  </div>
</nav>

front/templates/response.html
{% extends 'layout.html' %}
{% block content %}


<div class="card" style="width: 18rem;">
   <form action="{% url 'post:My_Jokes'%}">
    <div class="card-body">
      <h5 class="card-title">Chistesito de Chuck  </h5>
      <p class="card-text">{{ values.value }} </p>
      <input type="hidden" name="id" id="id" value="{{values.url}}">
      <a href="{% url 'post:Get' %}" class="btn btn-primary">Next</a>
      <button class="btn btn-danger" type="submit">agregar</button>
    </div>
   </form>
  </div>

{% endblock %}